### ISSUE TITLE
Structure Pre Game info HTML

### ISSUE THREAD

**Issue by tehbillis** [DevLearnCollective/MemorySnap#14]
This is the first thing that user sees, where we ask for their username/playername. Maybe also display the rules of the game and what it's about.

Items needed:

- Form with label, input, and button to input username
- area with either `<article> `or `<section>` elements that display usernames that are stored in LocalStorage.

Actions:
- When username is submitted, move on to memory snap game.
- If username exists, display error message stating so.
- When username is selected/clicked move on to memory snap game.

**Comment by T-Ingram** [comment]
When username is selected/clicked move on to memory snap game. - (Moved to own issue, #15)
