### ISSUE TITLE
Save Username To Local Storage - Javascript

### ISSUE THREAD

**Issue by tehbillis** [DevLearnCollective/MemorySnap#15]
Add javascript functionality to save username to localstorage.

Create a javascript function that creates a new user object and then calls another function that takes the user object as an argument and then  saves it to the localstorage.

Logic Flow:
First Step
- Create user button is clicked on pre game view.
- Event handler for the button calls the createUser function, and passes in the username from the username input.

Second Step
- If username doesn't exist in localstorage then continue. else return error.
- createUser function creates a new user object.
- Call saveUser function from within the createUser function.
- clear pre game view from the page.
- change view to game view.

Third Step
- saveUser function will parse localStorage to a variable, it will be an array of user objects.
- push the new user to the variable.
- save the variable to the localstorage.

Example Call to saveUser function:

`saveUser(userObject);`

**Comment by T-Ingram** [comment]
First step done.

Second step done.

Third step done.
